// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/index.tsx";
import * as $$0 from "./islands/Combinations.tsx";
import * as $$1 from "./islands/NumberBox.tsx";
import * as $$2 from "./islands/NumberSelectors.tsx";

const manifest = {
  routes: {
    "./routes/index.tsx": $0,
  },
  islands: {
    "./islands/Combinations.tsx": $$0,
    "./islands/NumberBox.tsx": $$1,
    "./islands/NumberSelectors.tsx": $$2,
  },
  baseUrl: import.meta.url,
};

export default manifest;
